# Generated by Django 5.2.7 on 2025-10-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
